import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const dashboard = fs.readFileSync(new URL('../src/views/v2/DashboardV2.vue', import.meta.url), 'utf8')
const layout = fs.readFileSync(new URL('../src/layouts/MainLayoutV2.vue', import.meta.url), 'utf8')
const gameVersionStatus = fs.readFileSync(new URL('../src/components/layout/GameVersionStatus.vue', import.meta.url), 'utf8')
const resourceStatus = fs.readFileSync(new URL('../src/components/layout/SystemResourceStatus.vue', import.meta.url), 'utf8')
const systemRefreshInterval = fs.readFileSync(new URL('../src/components/layout/SystemResourceRefreshInterval.vue', import.meta.url), 'utf8')
const roomRefreshInterval = fs.readFileSync(new URL('../src/components/layout/RoomRefreshIntervalSelect.vue', import.meta.url), 'utf8')
const refreshIntervalsComposable = fs.readFileSync(new URL('../src/composables/useDashboardRefreshIntervals.js', import.meta.url), 'utf8')
const resourceComposable = fs.readFileSync(new URL('../src/composables/useSystemResourceStatus.js', import.meta.url), 'utf8')
const serverWorkspace = fs.readFileSync(new URL('../src/views/servers/ServerWorkspace.vue', import.meta.url), 'utf8')
const apiV2 = fs.readFileSync(new URL('../src/api/v2.js', import.meta.url), 'utf8')

test('dashboard starts with useful room operations without redundant overview chrome', () => {
  assert.doesNotMatch(dashboard, /grid grid-cols-2 gap-x-5 gap-y-3 px-4 py-2\.5 sm:grid-cols-4/)
  assert.doesNotMatch(dashboard, /<CardHeader class="sr-only">/)
  assert.equal((dashboard.match(/<Card size="sm">/g) || []).length, 0)
  assert.doesNotMatch(dashboard, /dashboard\.summary\.(runningShards|onlinePlayers|roomsAndWorlds|hostLoad)/)
  assert.doesNotMatch(dashboard, /dashboard\.resources\.title/)
  assert.match(dashboard, /<ServerWorkspace id="room-operations" embedded/)
  assert.doesNotMatch(dashboard, /dashboard\.version\./)
  assert.doesNotMatch(dashboard, /dashboard\.(title|subtitle|lastUpdated|refreshAll)/)
  assert.doesNotMatch(dashboard, /roomOperations|deploymentPackaging/)
  assert.doesNotMatch(dashboard, /dashboard\.roomsOverview\.openControl/)
  assert.doesNotMatch(dashboard, /path: '\/servers\/workspace'/)
  assert.doesNotMatch(dashboard, /<WorldLog|components\/WorldLog/)
  assert.doesNotMatch(dashboard, /handleServerAction|cleanupFailedServer|openStartDialog|startDialogOpen/)
  assert.doesNotMatch(dashboard, /dashboard\.summary\.serverProcesses/)
  assert.doesNotMatch(dashboard, /dashboard\.servers\.totalInstances/)
  assert.doesNotMatch(dashboard, /flex flex-col gap-5 pt-1/)
})

test('global header separates lightweight system refreshes from room world polling', () => {
  assert.match(layout, /<ManagementScopeSwitch v-if="hasMachineScope"/)
  assert.match(layout, /<SystemResourceStatus v-if="hasMachineScope" class="hidden md:flex"/)
  assert.match(layout, /<GameVersionStatus v-if="hasMachineScope"/)
  assert.match(gameVersionStatus, /dashboard\.version\.officialGame/)
  assert.doesNotMatch(gameVersionStatus, /dashboard\.version\.localSteamBuild/)
  assert.doesNotMatch(gameVersionStatus, /dashboard\.version\.latestSteamBuild/)
  assert.match(gameVersionStatus, /fleetTargetMetadata\(target\)/)
  assert.match(gameVersionStatus, /fleetTargetSteamVersions\(target\)/)
  assert.match(gameVersionStatus, /fleetVersionChannels\.length > 1/)
  assert.match(gameVersionStatus, /gameReleases\.nodes\.steamDetails/)
  assert.match(gameVersionStatus, /<Popover\b/)
  assert.match(gameVersionStatus, /class="hidden min-w-0 items-center gap-1\.5 xl:flex"/)
  assert.match(resourceStatus, /<Popover\b/)
  assert.match(resourceStatus, /dashboard\.resources\.loadWindow/)
  assert.match(resourceStatus, /busiestCPUCore\(status\.value\.cpu_core_usage\)/)
  assert.match(resourceStatus, /systemLoadSeverity\(status\.value\.cpu_load5, loadCapacity\.value\)/)
  assert.match(resourceStatus, /dashboard\.resources\.loadStates\.\$\{loadState\.key\}/)
  assert.match(resourceStatus, /loadStateBadgeVariant\(\)/)
  assert.match(resourceStatus, /loadIsOverloaded \? 'text-destructive' : 'text-muted-foreground'/)
  assert.match(resourceStatus, /cpuAverageUsage = computed\(\(\) => status\.value\.cpu_usage\)/)
  assert.match(resourceStatus, /busiestCore\.value\?\.usage > CPU_CORE_ALERT_THRESHOLD/)
  assert.match(resourceStatus, /CPU_CORE_ALERT_THRESHOLD = 80/)
  assert.match(resourceStatus, /dashboard\.resources\.highCoreWarning/)
  assert.match(resourceStatus, /v-for="\(usage, index\) in status\.cpu_core_usage"/)
  assert.match(resourceStatus, /dashboard\.resources\.coreUsageAria/)
  assert.doesNotMatch(resourceStatus, /useDashboardV2/)
  assert.doesNotMatch(layout, /<Separator orientation="vertical"/)
  assert.doesNotMatch(resourceStatus, /<Separator orientation="vertical"/)
  assert.match(resourceStatus, /percentage\(value\) >= 90 && 'text-destructive'/)
  assert.match(refreshIntervalsComposable, /SYSTEM_RESOURCE_REFRESH_INTERVAL_MS = 5_000/)
  assert.match(refreshIntervalsComposable, /SYSTEM_RESOURCE_REFRESH_INTERVAL_OPTIONS_MS = Object\.freeze\(\[1_000, 2_000, 5_000, 10_000\]\)/)
  assert.match(refreshIntervalsComposable, /ROOM_REFRESH_INTERVAL_MS = 5_000/)
  assert.match(refreshIntervalsComposable, /ROOM_REFRESH_INTERVAL_OPTIONS_MS = Object\.freeze\(\[5_000, 10_000, 30_000, 60_000\]\)/)
  assert.match(resourceComposable, /useSystemResourceRefreshInterval\(\)/)
  assert.match(resourceComposable, /refreshSystemResourceStatus\(\{ silent: true \}\)/)
  assert.match(systemRefreshInterval, /<Select v-model="interval">/)
  assert.match(systemRefreshInterval, /useSystemResourceRefreshInterval/)
  assert.match(systemRefreshInterval, /dashboard\.resources\.systemRefreshIntervalAria/)
  assert.doesNotMatch(systemRefreshInterval, /useRoomRefreshInterval/)
  assert.match(roomRefreshInterval, /<Select v-model="interval">/)
  assert.match(roomRefreshInterval, /useRoomRefreshInterval/)
  assert.match(roomRefreshInterval, /dashboard\.resources\.roomRefreshIntervalAria/)
  assert.match(roomRefreshInterval, /<TimerReset/)
  assert.match(layout, /<GameVersionStatus\b[^>]*\/>[\s\S]*?<GlobalJobStatus\s*\/>[\s\S]*?<SystemResourceRefreshInterval\s*\/>[\s\S]*?<LanguageSwitch\s*\/>/)
  assert.doesNotMatch(layout, /RoomRefreshIntervalSelect/)
  assert.match(serverWorkspace, /<RoomRefreshIntervalSelect\s*\/>[\s\S]*?<Tooltip>[\s\S]*?@click="manualRefreshWorkspace"/)
  assert.match(serverWorkspace, /manualRefreshWorkspace\(\)[\s\S]*?Promise\.all\([\s\S]*?roomModOverview\?\.refresh[\s\S]*?this\.refreshWorkspace\(\)/)
  assert.doesNotMatch(serverWorkspace, /runtimeObservationsV2API\.refresh/)
  assert.match(serverWorkspace, /useRoomRefreshInterval\(\)/)
  assert.doesNotMatch(dashboard, /useRoomRefreshInterval|setInterval|refreshRuntimeServers/)
  assert.match(serverWorkspace, /window\.setInterval\(\(\) => this\.refreshPollingWorkspace\(\), this\.refreshIntervalMs\)/)
  assert.match(serverWorkspace, /runtimeObservationState === 'live'[\s\S]*?Promise\.all\(\[this\.refreshPlayerStats\(\), this\.refreshWorldStates\(\)\]\)[\s\S]*?return this\.refreshWorkspace\(true\)/)
  assert.match(serverWorkspace, /if \(silent && this\.refreshInFlightCount > 0\) \{[\s\S]*?this\.runtimeRefreshPending = true[\s\S]*?return false/)
  assert.match(serverWorkspace, /this\.refreshInFlightCount === 0 && this\.runtimeRefreshPending[\s\S]*?void this\.refreshWorkspace\(true\)/)
  assert.doesNotMatch(serverWorkspace, /\}, 30000\)/)
  assert.match(resourceComposable, /document\.visibilityState === 'hidden'/)
  assert.match(resourceComposable, /if \(refreshPromise && refreshPromiseScope === scopeKey\) return refreshPromise/)
  assert.match(resourceComposable, /INITIAL_POLLING_GRACE_MS = 2_000/)
  assert.equal((resourceComposable.match(/startRefreshTimer\(Math\.max\(INITIAL_POLLING_GRACE_MS, refreshIntervalMs\.value\)\)/g) || []).length, 2)
  assert.match(resourceComposable, /window\.setTimeout\(async \(\) => \{[\s\S]*?await refreshSystemResourceStatus\(\{ silent: true \}\)[\s\S]*?startRefreshTimer\(\)/)
  assert.doesNotMatch(resourceComposable, /window\.setInterval/)
  assert.doesNotMatch(dashboard, /getDashboardStatus/)
})

test('fleet resources reuse the single-machine metric language without a wide table', () => {
  assert.match(resourceStatus, /v-for="machine in fleetMachines"/)
  assert.match(resourceStatus, /grid min-w-0 grid-cols-2 gap-x-5 gap-y-3 md:grid-cols-4/)
  assert.match(resourceStatus, /percentage\(machine\.resource\.cpu_usage\)/)
  assert.match(resourceStatus, /percentage\(machine\.resource\.memory_usage\)/)
  assert.match(resourceStatus, /percentage\(machine\.resource\.disk_usage\)/)
  assert.match(resourceStatus, /loadPercentage\(machine\.resource\.cpu_load5, machineLoadCapacity\(machine\)\)/)
  assert.match(resourceStatus, /dashboard\.resources\.coresThreads/)
  assert.match(resourceStatus, /dashboard\.resources\.loadWindow/)
  assert.match(resourceStatus, /v-for="\(usage, index\) in machine\.resource\.cpu_core_usage"/)
  assert.match(resourceStatus, /grid-cols-2 gap-x-4 gap-y-2 sm:grid-cols-3 md:grid-cols-6/)
  assert.match(resourceStatus, /machine\.resource\.cpu_core_usage\?\.length/)
  assert.match(resourceStatus, /machineSubtitle\(machine\)/)
  assert.match(resourceStatus, /machineTelemetryHint\(machine\)/)
  assert.match(resourceStatus, /dashboard\.resources\.agentMetricsIncompleteVersion/)
  assert.match(resourceStatus, /selectedNodeState/)
  assert.match(resourceStatus, /dashboard\.resources\.machineStates\.\$\{selectedNodeState\}/)
  assert.doesNotMatch(resourceStatus, /<table\b/)
  assert.doesNotMatch(resourceStatus, /overflow-x-auto/)
})

test('heavy operational tabs and external icon styles do not block the initial dashboard', () => {
  const index = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8')
  const main = fs.readFileSync(new URL('../src/main.js', import.meta.url), 'utf8')

  assert.match(serverWorkspace, /defineAsyncComponent\(\(\) => import\('@\/components\/WorldLog\.vue'\)\)/)
  assert.match(serverWorkspace, /defineAsyncComponent\(\(\) => import\('@\/components\/RoomChatPanel\.vue'\)\)/)
  assert.match(serverWorkspace, /v-if="activeOperation === 'logs' && selectedWorld"/)
  assert.match(serverWorkspace, /v-if="activeOperation === 'chat'"/)
  assert.doesNotMatch(main, /xterm\/css\/xterm\.css/)
  assert.doesNotMatch(index, /font-awesome|cdnjs\.cloudflare\.com/)
})

test('room workspace renders a stable skeleton before the first room response', () => {
  assert.match(serverWorkspace, /loading: true/)
  assert.match(serverWorkspace, /initialLoading\(\) \{\s*return this\.loading && this\.rooms\.length === 0 && !this\.loadError/)
  assert.match(serverWorkspace, /v-else-if="initialLoading"[\s\S]*?<Skeleton class="h-4 w-52"/)
  assert.match(serverWorkspace, /<RoomScopeSelect[^>]*:loading="initialLoading"/)
  assert.match(serverWorkspace, /<section\s+v-if="initialLoading"[\s\S]*?servers\.workspace\.loading[\s\S]*?<Card size="sm">/)
  assert.match(serverWorkspace, /<Empty v-else-if="!loadError && rooms\.length === 0">/)
  assert.doesNotMatch(serverWorkspace, /if \(roomsResult\.status === 'rejected'\) \{\s*this\.rooms = \[\]/)
})

test('initial layout consumers share stable read requests', () => {
  assert.match(apiV2, /authSessionCache = createAsyncResourceCache\(\{ ttlMs: 1_000 \}\)/)
  assert.match(apiV2, /capabilityCache = createAsyncResourceCache\(\{ ttlMs: 30_000 \}\)/)
  assert.match(apiV2, /gameVersionCache = createAsyncResourceCache\(\{ ttlMs: 1_000 \}\)/)
  assert.match(apiV2, /session: \(\) => authSessionCache\.load/)
  assert.match(apiV2, /capabilities: \(\{ fresh = false \} = \{\}\) => \{\s*if \(fresh\) capabilityCache\.invalidate\(\)\s*return capabilityCache\.load/)
  assert.match(apiV2, /version: \(\{ fresh = false, lightweight = false \} = \{\}\) =>/)
  assert.match(apiV2, /const cache = lightweight \? gameVersionSummaryCache : gameVersionCache/)
  assert.match(apiV2, /if \(fresh\) cache\.invalidate\(\)/)
  assert.match(apiV2, /client\.get\('\/game\/version', \{[\s\S]*runtimeTarget: false,[\s\S]*timeout: lightweight \? GAME_VERSION_REQUEST_TIMEOUT/)
})
