import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

const dashboard = fs.readFileSync(new URL('../src/views/v2/DashboardV2.vue', import.meta.url), 'utf8')
const layout = fs.readFileSync(new URL('../src/layouts/MainLayoutV2.vue', import.meta.url), 'utf8')
const resourceStatus = fs.readFileSync(new URL('../src/components/layout/SystemResourceStatus.vue', import.meta.url), 'utf8')
const systemRefreshInterval = fs.readFileSync(new URL('../src/components/layout/SystemResourceRefreshInterval.vue', import.meta.url), 'utf8')
const roomRefreshInterval = fs.readFileSync(new URL('../src/components/layout/RoomRefreshIntervalSelect.vue', import.meta.url), 'utf8')
const refreshIntervalsComposable = fs.readFileSync(new URL('../src/composables/useDashboardRefreshIntervals.js', import.meta.url), 'utf8')
const resourceComposable = fs.readFileSync(new URL('../src/composables/useSystemResourceStatus.js', import.meta.url), 'utf8')
const serverWorkspace = fs.readFileSync(new URL('../src/views/servers/ServerWorkspace.vue', import.meta.url), 'utf8')

test('dashboard starts with useful room operations without redundant overview chrome', () => {
  assert.doesNotMatch(dashboard, /grid grid-cols-2 gap-x-5 gap-y-3 px-4 py-2\.5 sm:grid-cols-4/)
  assert.doesNotMatch(dashboard, /<CardHeader class="sr-only">/)
  assert.equal((dashboard.match(/<Card size="sm">/g) || []).length, 0)
  assert.doesNotMatch(dashboard, /dashboard\.summary\.(runningShards|onlinePlayers|roomsAndWorlds|hostLoad)/)
  assert.doesNotMatch(dashboard, /dashboard\.resources\.title/)
  assert.match(dashboard, /<ServerWorkspace id="room-operations" embedded/)
  assert.match(dashboard, /dashboard\.version\.currentVersion/)
  assert.match(dashboard, /dashboard\.version\.latestVersion/)
  assert.doesNotMatch(dashboard, /dashboard\.(title|subtitle|lastUpdated|refreshAll)/)
  assert.doesNotMatch(dashboard, /roomOperations|deploymentPackaging/)
  assert.doesNotMatch(dashboard, /dashboard\.roomsOverview\.openControl/)
  assert.doesNotMatch(dashboard, /path: '\/servers\/workspace'/)
  assert.match(dashboard, /router\.push\('\/servers\/releases'\)/)
  assert.match(dashboard, /dashboard\.version\.openUpdateHelp/)
  assert.match(dashboard, /v-if="canInstallGame"/)
  assert.match(dashboard, /v-else-if="isVersionOutdated && canUpdateGame"/)
  assert.match(dashboard, /@click="updateGame"/)
  assert.doesNotMatch(dashboard, /<WorldLog|components\/WorldLog/)
  assert.doesNotMatch(dashboard, /handleServerAction|cleanupFailedServer|openStartDialog|startDialogOpen/)
  assert.doesNotMatch(dashboard, /dashboard\.summary\.serverProcesses/)
  assert.doesNotMatch(dashboard, /dashboard\.servers\.totalInstances/)
  assert.doesNotMatch(dashboard, /flex flex-col gap-5 pt-1/)
})

test('global header separates lightweight system refreshes from room world polling', () => {
  assert.match(layout, /<SystemResourceStatus class="ml-auto"/)
  assert.match(resourceStatus, /<Popover\b/)
  assert.match(resourceStatus, /dashboard\.resources\.loadWindow/)
  assert.match(resourceStatus, /busiestCPUCore\(status\.value\.cpu_core_usage\)/)
  assert.match(resourceStatus, /cpuAverageUsage = computed\(\(\) => status\.value\.cpu_usage\)/)
  assert.match(resourceStatus, /busiestCore\.value\?\.usage > CPU_CORE_ALERT_THRESHOLD/)
  assert.match(resourceStatus, /CPU_CORE_ALERT_THRESHOLD = 80/)
  assert.match(resourceStatus, /dashboard\.resources\.highCoreWarning/)
  assert.match(resourceStatus, /v-for="\(usage, index\) in status\.cpu_core_usage"/)
  assert.match(resourceStatus, /dashboard\.resources\.coreUsageAria/)
  assert.doesNotMatch(resourceStatus, /useDashboardV2/)
  assert.doesNotMatch(layout, /<Separator orientation="vertical"/)
  assert.doesNotMatch(resourceStatus, /<Separator orientation="vertical"/)
  assert.match(resourceStatus, /percentage\(value\) >= 90 && 'text-destructive'/)
  assert.match(refreshIntervalsComposable, /SYSTEM_RESOURCE_REFRESH_INTERVAL_MS = 5_000/)
  assert.match(refreshIntervalsComposable, /SYSTEM_RESOURCE_REFRESH_INTERVAL_OPTIONS_MS = Object\.freeze\(\[1_000, 2_000, 5_000, 10_000\]\)/)
  assert.match(refreshIntervalsComposable, /ROOM_REFRESH_INTERVAL_MS = 5_000/)
  assert.match(refreshIntervalsComposable, /ROOM_REFRESH_INTERVAL_OPTIONS_MS = Object\.freeze\(\[5_000, 10_000, 30_000, 60_000\]\)/)
  assert.match(resourceComposable, /useSystemResourceRefreshInterval\(\)/)
  assert.match(resourceComposable, /refreshSystemResourceStatus\(\{ silent: true \}\)/)
  assert.match(systemRefreshInterval, /<Select v-model="interval">/)
  assert.match(systemRefreshInterval, /useSystemResourceRefreshInterval/)
  assert.match(systemRefreshInterval, /dashboard\.resources\.systemRefreshIntervalAria/)
  assert.doesNotMatch(systemRefreshInterval, /useRoomRefreshInterval/)
  assert.match(roomRefreshInterval, /<Select v-model="interval">/)
  assert.match(roomRefreshInterval, /useRoomRefreshInterval/)
  assert.match(roomRefreshInterval, /dashboard\.resources\.roomRefreshIntervalAria/)
  assert.match(roomRefreshInterval, /<TimerReset/)
  assert.match(layout, /<GlobalJobStatus\s*\/>[\s\S]*?<SystemResourceRefreshInterval\s*\/>[\s\S]*?<LanguageSwitch\s*\/>/)
  assert.doesNotMatch(layout, /RoomRefreshIntervalSelect/)
  assert.match(serverWorkspace, /<RoomRefreshIntervalSelect\s*\/>[\s\S]*?<Tooltip>[\s\S]*?@click="refreshWorkspace\(\)"/)
  assert.match(serverWorkspace, /useRoomRefreshInterval\(\)/)
  assert.match(dashboard, /useRoomRefreshInterval\(\)/)
  assert.match(serverWorkspace, /window\.setInterval\(\(\) => this\.refreshWorkspace\(true\), this\.refreshIntervalMs\)/)
  assert.match(serverWorkspace, /if \(silent && this\.refreshInFlightCount > 0\) return false/)
  assert.doesNotMatch(serverWorkspace, /\}, 30000\)/)
  assert.match(resourceComposable, /document\.visibilityState === 'hidden'/)
  assert.match(resourceComposable, /if \(refreshPromise\) return refreshPromise/)
  assert.doesNotMatch(dashboard, /getDashboardStatus/)
})
