import { markRaw } from 'vue'
import * as ElementPlusIcons from '@element-plus/icons-vue'

const iconGroups = {
  ArrowDown: ['arrow-down'],
  ArrowRight: ['arrow-right'],
  Back: ['back'],
  Bell: ['alarm-clock'],
  Box: ['box'],
  Calendar: ['date'],
  Check: ['check', 'success'],
  CircleClose: ['close', 'error'],
  Coin: ['coin'],
  CollectionTag: ['collection-tag'],
  Connection: ['connection', 'network', 'shard'],
  CopyDocument: ['copy-document', 'document-copy'],
  Cpu: ['cpu'],
  DataAnalysis: ['data-analysis', 'data-line'],
  Delete: ['delete'],
  Document: ['document'],
  Download: ['download'],
  Edit: ['edit'],
  Files: ['s-management'],
  Flag: ['flag'],
  Folder: ['folder'],
  FolderAdd: ['folder-add'],
  Grid: ['s-grid'],
  Heart: ['heart'],
  Hide: ['hide'],
  House: ['s-home'],
  InfoFilled: ['info', 'info-circle'],
  Key: ['key'],
  Lightning: ['lightning'],
  Loading: ['loading'],
  Location: ['location', 'map-location', 'earth'],
  Lock: ['lock'],
  MagicStick: ['magic-stick'],
  Management: ['s-data'],
  Menu: ['more', 's-fold', 's-unfold'],
  Monitor: ['monitor', 's-platform', 'platform-eleme'],
  Moon: ['moon', 'moon-night', 'full-moon'],
  MostlyCloudy: ['heavy-rain'],
  Odometer: ['odometer'],
  Operation: ['s-operation', 's-opportunity', 's-promotion', 's-tools', 'terminal', 'game', 'system', 'steam'],
  Picture: ['picture-outline'],
  Plus: ['plus'],
  Promotion: ['upload2'],
  QuestionFilled: ['question'],
  Refresh: ['refresh'],
  RefreshLeft: ['refresh-left'],
  RefreshRight: ['refresh-right'],
  Remove: ['remove'],
  Search: ['search'],
  Setting: ['setting'],
  Star: ['star-off'],
  StarFilled: ['star-on', 'trophy'],
  Sunny: ['sunny'],
  Sunrise: ['sunrise'],
  Sunset: ['sunset'],
  Timer: ['time'],
  Upload: ['upload'],
  User: ['user'],
  UserFilled: ['user-solid', 's-custom'],
  VideoPause: ['video-pause'],
  VideoPlay: ['video-play'],
  View: ['view'],
  Warning: ['warning', 'warning-outline'],
  Umbrella: ['umbrella'],
  Apple: ['apple']
}

export function installLegacyIcons(app) {
  Object.entries(iconGroups).forEach(([componentName, legacyNames]) => {
    const icon = markRaw(ElementPlusIcons[componentName] || ElementPlusIcons.Operation)
    legacyNames.forEach(name => app.component(`el-icon-${name}`, icon))
  })
}
